"""
Regex to DFA conversion and validation module.

This module validates regex patterns and converts them to DFAs for use in eBPF.
Matching is unanchored — the pattern can match anywhere inside the input string.
This is achieved by prepending ".*" to the pattern before DFA construction.

The validation ensures:
1. The regex is syntactically valid
2. Only supported regex features are used
3. The resulting unanchored DFA has at most MAX_REGEX_DFA_STATES states
4. The DFA has at least one accepting state

The actual DFA used at runtime is generated by C++ userspace code.
This Python code only validates that conversion is possible.
"""

import re
from dataclasses import dataclass
from typing import Set, Tuple, Optional
from greenery import parse as greenery_parse
from greenery.fsm import Fsm

from constants import MAX_REGEX_DFA_STATES


@dataclass
class RegexValidationResult:
    """Result of regex validation."""
    is_valid: bool
    error_message: Optional[str] = None
    num_states: int = 0
    num_accepting_states: int = 0


SUPPORTED_FEATURES_HELP = """
Supported regex features:
  - Literal characters (a, b, 1, 2, etc.)
  - Character classes: [abc], [a-z], [^abc]
  - Predefined classes: \\d, \\w, \\s (and negations \\D, \\W, \\S)
  - Dot (.) matches any character
  - Quantifiers: *, +, ?, {n}, {n,}, {n,m}
  - Alternation: a|b
  - Grouping: (abc)
  - Anchors: ^ (start), $ (end)
  - Case-insensitive flag: (?i)
  - Escape sequences: \\., \\*, \\+, etc.

NOT supported (will cause DFA state explosion or are impossible in DFA):
  - Backreferences: \\1, \\2, etc.
  - Lookahead: (?=...), (?!...)
  - Lookbehind: (?<=...), (?<!...)
  - Atomic groups: (?>...)
  - Possessive quantifiers: *+, ++, ?+
  - Named groups: (?P<name>...)
  - Conditional patterns: (?(id)yes|no)
  - Recursion: (?R), (?0)
"""


UNSUPPORTED_PATTERNS = [
    (r'\\[1-9]', "Backreferences (\\1, \\2, etc.) are not supported"),
    (r'\(\?=', "Positive lookahead (?=...) is not supported"),
    (r'\(\?!', "Negative lookahead (?!...) is not supported"),
    (r'\(\?<=', "Positive lookbehind (?<=...) is not supported"),
    (r'\(\?<!', "Negative lookbehind (?<!...) is not supported"),
    (r'\(\?>', "Atomic groups (?>...) are not supported"),
    (r'\(\?P<', "Named groups (?P<name>...) are not supported"),
    (r'\(\?\(', "Conditional patterns are not supported"),
    (r'\(\?R\)', "Recursive patterns are not supported"),
    (r'\(\?[0-9]+\)', "Recursive patterns are not supported"),
    (r'[*+?]\+', "Possessive quantifiers (*+, ++, ?+) are not supported"),
]


def _check_unsupported_features(pattern: str) -> Optional[str]:
    """
    Check if the pattern contains unsupported regex features.
    Returns an error message if unsupported features are found, None otherwise.
    """
    for regex, error_msg in UNSUPPORTED_PATTERNS:
        if re.search(regex, pattern):
            return error_msg
    return None


def _preprocess_pattern_for_greenery(pattern: str) -> str:
    """
    Preprocess the regex pattern to make it compatible with greenery.
    
    Greenery has limited support for some regex features, so we need to
    expand them manually.
    """
    result = pattern
    
    if result.startswith("(?i)"):
        result = result[4:]
        result = _make_case_insensitive(result)
    
    result = _expand_shorthand_classes(result)
    
    return result


def _make_case_insensitive(pattern: str) -> str:
    """
    Convert a pattern to case-insensitive by expanding [a-z] to [a-zA-Z], etc.
    This is a simplified implementation that handles common cases.
    """
    result = []
    i = 0
    in_char_class = False
    
    while i < len(pattern):
        char = pattern[i]
        
        if char == '\\' and i + 1 < len(pattern):
            result.append(char)
            result.append(pattern[i + 1])
            i += 2
            continue
        
        if char == '[':
            in_char_class = True
            result.append(char)
            i += 1
            continue
        
        if char == ']':
            in_char_class = False
            result.append(char)
            i += 1
            continue
        
        if not in_char_class and char.isalpha():
            lower = char.lower()
            upper = char.upper()
            if lower != upper:
                result.append(f'[{lower}{upper}]')
            else:
                result.append(char)
        else:
            result.append(char)
        i += 1
    
    return ''.join(result)


def _expand_shorthand_classes(pattern: str) -> str:
    """
    Expand shorthand character classes that greenery doesn't support.
    """
    replacements = [
        (r'\\d', '[0-9]'),
        (r'\\D', '[^0-9]'),
        (r'\\w', '[a-zA-Z0-9_]'),
        (r'\\W', '[^a-zA-Z0-9_]'),
        (r'\\s', '[ \\t\\n\\r\\f\\v]'),
        (r'\\S', '[^ \\t\\n\\r\\f\\v]'),
    ]
    
    result = pattern
    for shorthand, expansion in replacements:
        temp_result = []
        i = 0
        while i < len(result):
            if result[i:i+2] == shorthand.replace('\\\\', '\\'):
                if i > 0 and result[i-1] == '\\':
                    temp_result.append(result[i])
                else:
                    temp_result.append(expansion)
                    i += 1
            else:
                temp_result.append(result[i])
            i += 1
        result = ''.join(temp_result)
    
    return result


def validate_regex(pattern: str) -> RegexValidationResult:
    """
    Validate a regex pattern and check if it can be converted to a DFA.
    
    Args:
        pattern: The regex pattern to validate
        
    Returns:
        RegexValidationResult with validation status and details
    """
    if not pattern:
        return RegexValidationResult(
            is_valid=False,
            error_message="Empty regex pattern is not allowed"
        )
    
    try:
        re.compile(pattern)
    except re.error as e:
        return RegexValidationResult(
            is_valid=False,
            error_message=f"Invalid regex syntax: {e}"
        )
    
    unsupported_error = _check_unsupported_features(pattern)
    if unsupported_error:
        return RegexValidationResult(
            is_valid=False,
            error_message=unsupported_error
        )
    
    try:
        preprocessed = _preprocess_pattern_for_greenery(pattern)
        unanchored = ".*" + preprocessed
        lego = greenery_parse(unanchored)
        fsm: Fsm = lego.to_fsm()
        
        fsm = fsm.reduce()
        
        num_states = len(fsm.states)
        num_accepting = len(fsm.finals)
        
        if num_states > MAX_REGEX_DFA_STATES:
            return RegexValidationResult(
                is_valid=False,
                error_message=f"Regex produces too many DFA states: {num_states} (max {MAX_REGEX_DFA_STATES}). "
                             f"Simplify the pattern.",
                num_states=num_states,
                num_accepting_states=num_accepting
            )
        
        if num_accepting == 0:
            return RegexValidationResult(
                is_valid=False,
                error_message="Regex produces a DFA with no accepting states. "
                             "This means the pattern can never match.",
                num_states=num_states,
                num_accepting_states=0
            )
        
        return RegexValidationResult(
            is_valid=True,
            num_states=num_states,
            num_accepting_states=num_accepting
        )
        
    except Exception as e:
        return RegexValidationResult(
            is_valid=False,
            error_message=f"Failed to convert regex to DFA: {e}"
        )


def validate_regex_or_raise(pattern: str, context: str = "") -> None:
    """
    Validate a regex pattern and raise an exception if invalid.
    
    Args:
        pattern: The regex pattern to validate
        context: Optional context string for error messages (e.g., field name)
        
    Raises:
        Exception: If the regex is invalid
    """
    result = validate_regex(pattern)
    if not result.is_valid:
        ctx_prefix = f"{context}: " if context else ""
        raise Exception(f"{ctx_prefix}{result.error_message}")
